version: "3.8"
services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
    image: murilochianfa/protobuffed-drogon-frontend:1.0.0
    container_name: front
    hostname: front
    ports:
      - 80:80/tcp
    volumes:
      - ./front:/app
      - ./protos:/app/protos

  drogon:
    build:
      context: sender
      dockerfile: Dockerfile
    image: murilochianfa/protobuffed-drogon-sender:1.0.0
    container_name: drogon
    hostname: drogon
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./sender:/drogon/app
      - ./protos:/drogon/app/protos
