version: "3.8"
services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
    image: front
    container_name: front
    hostname: front
    ports:
      - 80:80/tcp
    volumes:
      - ./front:/app
      - ./protos:/app/protos

  drogon:
    build:
      context: sender
      dockerfile: Dockerfile
    image: drogon
    container_name: drogon
    hostname: drogon
    ports:
      - 8848:8848
    volumes:
      - ./sender:/drogon/app
      - ./protos:/drogon/app/protos
