'use strict'; // code generated by pbf v3.2.1

// Chart ========================================

var Chart = self.Chart = {};

Chart.read = function (pbf, end) {
    return pbf.readFields(Chart._readField, {id: 0, name: ""}, end);
};
Chart._readField = function (tag, obj, pbf) {
    if (tag === 2) obj.id = pbf.readVarint(true);
    else if (tag === 1) obj.name = pbf.readString();
};
Chart.write = function (obj, pbf) {
    if (obj.id) pbf.writeVarintField(2, obj.id);
    if (obj.name) pbf.writeStringField(1, obj.name);
};
